### ISSUE TITLE
Use of `const` in README

### ISSUE THREAD

**Issue by chuckpreslar** [codemix/babel-plugin-macros#1]
As the arrays in your README example are being modified after declaration, they really shouldn't be constants but regular variables (this may even throw an error once ES6 is fully supported).

```javascript
const filtered = []; // Should be `let` or `var` as we are pushing values into array after declaration.
for (let i = 0; i < input.length; i++) {
  if (visitor(input[i], i, input)) {
    filtered.push(input[i]);
  }
}
```

P.S. Great work!

**Comment by phpnode** [comment]
@chuckpreslar thanks, but this is not a mistake and will not cause an error in future versions of ECMAScript :)

`const` means that the variable being declared will *always point to the same reference*, it does not mean that the value being referenced is itself immutable (although that is indeed the case when initializing with primitives like strings). If you want to make an object immutable then you must use `Object.freeze()` , e.g.

```js
const filtered = Object.freeze([]); // will always be an empty array
filtered = [1,2,3]; // SyntaxError
filtered.push(123); // nope
```
 
I'd imagine this misunderstanding is fairly common.
