### ISSUE TITLE
Cycle recursion in macros calls

### ISSUE THREAD

**Issue by Gvozd** [codemix/babel-plugin-macros#10]
Now is blocked, but has some idea for support
This simple example^

``` javascript
DEFINE_MACRO(FOO, () => {BAR()});
DEFINE_MACRO(BAR, () => {FOO()});
export default function demo() {
  return FOO();
}
```

Maybe transofm to something like

``` javascript
export default function demo() {
  function BAR() {
    BAR();
  }
  return BAR();
}
```

I mean cases where a cyclic recursion at compile time but finite at runtime
Recursion that infinite at runtime(like my example), remain endless infinite at runtime :)

**Comment by graingert** [comment]
tail-recursive macros should be transformable to switch/case GOTOs

**Comment by graingert** [comment]
```js
DEFINE_MACRO(FOO, () => {BAR()});
DEFINE_MACRO(BAR, () => {FOO()});
export default function demo() {
  return FOO();
}
```

```js
export default function demo() {
    var _state = 'FOO';
    while(_state != 'END') {
        switch(_state) {
            case 'FOO':
              _state = 'BAR';
              break;
            case 'BAR':
              _state = 'FOO';
              break;
        }
    }
}
```

**Comment by graingert** [comment]
of course if a macro isn't tail recursive you can use a software stack:
```js
DEFINE_MACRO(FIB, (n) => {
    if(n === 0) {
        return 0;
    }
    if (n === 1) {
      return 1;
     }
    return FIB(n - 1) + FIB(n - 2);
}

export default function demo() {
  return FIB(2);
}
```
```js
export default function demo() {
    var _stack = [{caller: 'END', callee: 'FIB-0', frame: {n: 1}}];
    var _head;
    var _ret = undefined;
    while(true) {
        var _head = _stack.pop();
        switch(_head.callee) {
            case 'END':
                return _ret;
            case 'FIB-0':
              if(_head.frame.n === 0) {
                  _ret = 0;
                  break;
              }
              if {_head.frame.n === 1) {
                 _ret = 1;
                 break;
              }
              _stack.push({macro: 'FIB-1', frame: {n: _head.frame.n -1});
              break;
            case 'FIB-1':
               ... // I need to learn how compilers work some more....
        }
    }
}
```

**Comment by Gvozd** [comment]
@graingert , Thanks, this look like a good idea.
But unfortunately, I have no time to work on this plugin at the moment
If you need this functionality now, I am happy to accept PR

**Comment by graingert** [comment]
@Gvozd too much of a pain imhop. You'd need a full JS parse/transpiler.

**Comment by Gvozd** [comment]
@graingert Maybe
But when the generators are being transformed, similar transpilation is worked?
Maybe this code re-usable, and can transform each function to switch-case(inner macro-call separate states, instead yield-expression), and some combine two switch-cases to one switch-case with all states, and local variables?
But I have no time at now, to investigate this, and implement.

But even if my guesses are correct, this is still an uneasy task

**Comment by Gvozd** [comment]
closed due to inactivity
