### ISSUE TITLE
auto-macros option

### ISSUE THREAD

**Issue by Gvozd** [codemix/babel-plugin-macros#15]
I propose to add an experimental option
In some cases, you can automatically deploy function macros
1. function is FunctionDeclaration
2. All usages in scope - only direct calls (not func.call/apply, pass to another function as argument or other)
3. automaticaly use this function as macros

In future maybe some more rules

This planned implement as additional option for plugin (by default is off)

**Comment by phpnode** [comment]
I think this belongs in a different plugin, I actually already started work on something similar but it's very early days, it does function inlining and constant propagation etc. I'll push it to github later and add you.
