### ISSUE TITLE
can this be used to replace `console.log`?

### ISSUE THREAD

**Issue by olegstepura** [codemix/babel-plugin-macros#17]
Hi!

Can this plugin be used to replace invocations like `object.method`,  4ex to rewrite `console.log` with `logger.debug`?

```js
macro: {
  "console.log" = () => logger.debug(__TIMESTAMP, ...arguments)
}
```
so that each time I write `console.log('xxx', 'yyy')` it is rewritten in compile time to `logger.debug(__TIMESTAMP, 'xxx', 'yyy')`

**Comment by phpnode** [comment]
It can't do this kind of transformation directly, it operates on identifiers not member expressions, but it's quite straight forward to write a babel plugin to do this yourself:

http://astexplorer.net/#/gist/b7380fd0baf4ca7bf24e1cf839877c94/7c2967dabe1ffdf1d231969d18c86496e0567ee1

**Comment by phpnode** [comment]
Also you might find this plugin useful - https://github.com/codemix/babel-plugin-trace

**Comment by olegstepura** [comment]
Wow, what a great gist. And the mentioned plugin looks great as well. Thanks! Will investigate this deeper.
