### ISSUE TITLE
Is this package active? If not, can I have the name?

### ISSUE THREAD

**Issue by kentcdodds** [codemix/babel-plugin-macros#18]
Hi! I'm actively working on [`babel-macros`](https://github.com/kentcdodds/babel-macros) and it's picking up steam. Things are working great, however due to changes in babel@7, the package needs to have the `babel-plugin-` prefix or folks will have to use the `module:` prefix in their config. Learn more about this here: https://github.com/kentcdodds/babel-macros/issues/41

I'd prefer to avoid having to call it `babel-plugin-babel-macros` because that's a bit redundant. So, would you be willing to give me `babel-plugin-macros`?

If not that's fine, but I thought I'd ask anyway. Thanks!

**Comment by phpnode** [comment]
hey Kent!, the project isn't really active any more and I much prefer the babel-macros approach anyway, so I'd be happy to hand it over

**Comment by kentcdodds** [comment]
Super! Thank you! I'll publish a 2.0.0 soonish. Thank you!

**Comment by kentcdodds** [comment]
It's been published. Thank you again!
