### ISSUE TITLE
Are these really macros?

### ISSUE THREAD

**Issue by bitmage** [codemix/babel-plugin-macros#3]
A macro, in the sense that I'm used to, means that it is reading an unevaluated expression as an input, has the ability to transform and introspect that expression, and it is returning an unevaluated expression as an output.  It is doing its work at "read" or "compile" time, not at run time.  So to take your example of:

```javascript
DEFINE_MACRO(MAP, (input, visitor) => {
  const length = input.length;
  const result = new Array(length);
  for (let i = 0; i < length; i++) {
    result[i] = visitor(input[i], i, input);
  }
  return result;
});

function demo () {
  return MAP([1,2,3,4], item => item + 1);
}
```

Your output looks more like the result of an [in-line function](http://www.drdobbs.com/the-new-c-inline-functions/184401540).  In the more lispy sense of a macro, I would expect this to return:

```javascript
function demo () {
  return [2,3,4,5];
}
```

In order to do that, we need to be able to manipulate symbols/AST as objects.  [Lisps do this without grammar complexities](http://learnxinyminutes.com/docs/clojure-macros/), [other languages](http://metalua.luaforge.net/quicktour.html) have to deal with grammar rules.  In both cases they have a sort of quoting syntax for describing the returned expression(s).

Do you know if this is possible as a Babel plugin?  I'm curious, because this would be very powerful indeed.  It lets us do far more than performance operations - it lets us to some degree rewrite the semantics of the language.

**Comment by phpnode** [comment]
It is possible to do but pretty difficult in the general case. Your example would be pretty trivial but most cases would be much more complicated.

**Comment by Gvozd** [comment]
I also think that this task is difficult

Also I think that issue out of scope plugin
JavaScript closer to C, than to LISP
So we have much work for support subset of C-macros
