### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by PAEz** [codemix/babel-plugin-macros#4]
Id like the ability to...
Have a macro that can return a different function according to what macro its chained to and if its not chained to a macro then dont do anything the person actually wants the native function.
Know thats a mouthful ;) hope ya get my meaning.
If I had that ability I could have some fun.

**Comment by phpnode** [comment]
I think I understand what you mean but it sounds totally unreadable! Something like this?

```js
doSomething(); // Just calls doSomething()

doSomething().foo(); // Calls a macro like "doSomething_foo"
```

I'm not sure how much of a good idea this is, what do you really want to do?

**Comment by PAEz** [comment]
doSomething has to be a macro to or just use the noraml foo.
I just wanna try the idea of a dom selector thingy that is all macros.
So...
$ becomes document.querySelector
and $$ is document.querySelectorAll
Then a macro called on does one function if chained...dam I just thought of a problem of the further down the chain it needs to know what the very first one is, bumma, didnt think of that....ok now I want the ability to know what the first function the chain had was ;P
Um, yeah...
and then the chaining functions know if to return the nodelist based function or the single element one.

Its just an idea Ive always wanted to look at, sorry if its dumb ;)

**Comment by PAEz** [comment]
The more I think about it the more I realise I didnt think about it...theres other problems with the chaining idea.
Sorry to waste ya time
...still like the idea ;P
