### ISSUE TITLE
Wrong execution order in expression

### ISSUE THREAD

**Issue by Gvozd** [codemix/babel-plugin-macros#8]
Simpliest test for this bug

``` javascript
export default function demo () {
  var steps = [];
  DEFINE_MACRO(FOO, () => {steps.push(2);});
  (steps.push(1), FOO());
  function BAR(){steps.push(4);}
  (steps.push(3), BAR());
  return steps;// expected [1, 2, 3, 4] but got [2, 1, 3, 4]
}
```

Possible solutions:
1. Allow macros only in simple assignment expressions, like `a=MACRO();`
Maybe another simple variants will be allowed.
Not usefull for end-user
2. If macro has executable siblings, calculate it before main expression in correct order
For example, code

``` javascript
var a = {
  foo: 123,//not executable,
  bar: func(),//executable
  baz: qwe.asd,//posible executable(getter)
  bat: {
    qwe: func2(),//executable
    asd: MACRO(),
    zxc: func3(),//executable, but after macro-definition
  }
};
```

transformed to like this

``` javascript
var tmp1 = func(),
  tmp2 = qwe.asd,
  tmp3 = func2();
var a = {
  foo: 123,
  bar: tmp1,
  baz: tmp2,
  bat: {
    qwe: tmp3,
    asd: MACRO(),
    zxc: func3(),//executable, but after macro-definition
  }
};
```

This solution is harder for implement, and generate less human readable code

**Comment by phpnode** [comment]
The latter is definitely the way to go but it's painful. We should look and see how babel's async function transform does it, because it requires similar tricks.

**Comment by Gvozd** [comment]
I also think return to this trouble later
Or maybe somebody join to this plugin development)

Thanks for idea to look babel async function transform

Also, good news - were frequently to download the plugin from npm
[![NPM](https://nodei.co/npm-dl/babel-plugin-macros.png?months=1)](https://nodei.co/npm/babel-plugin-macros/)

**Comment by Gvozd** [comment]
closed due to inactivity
